### ISSUE TITLE
No longer supported?

### ISSUE THREAD

**Issue by trusktr** [desandro/doc-ready#10]
But there's a reason to support it: because, for people who are naive, and they run code like you suggest:

```js
document.addEventListener( 'DOMContentLoaded', function( event ) {
  console.log("DOM is ready. Let's party");
});
```

that `console.log` will never fire if the document is already ready when that script was evaluated. It's good enough reason to wrap it so that it fires even if the DOM is already loaded, because that's what many people expect considering that's the standard that jQuery set for everyone.

Better:

```js
async function documentReady( passThrough ) {
    if (document.readyState === 'loading') {
        await new Promise(function(resolve) {
            document.addEventListener('DOMContentLoaded', resolve)
        })
    }

    return passThrough
}
```

then

```js
fetch(...)
  .then(...)
  .then(...)
  .then(documentReady) // passThrough
  .then(() => console.log('ready to party!'))

// or

async function main() {
  await documentReady()
  console.log('party!')
}
```

and that way it always works.

**Comment by desandro** [comment]
Hey, thanks for the recommendation. This library was intended to be a polyfill for IE8. Suggesting ES6 code may be useful if you're already supporting that. But I feel its a different use case for this library.

I'll leave this issue open for other's visibility.
