### ISSUE TITLE
Cannot read property 'bind' of undefined  doc-ready.js:61 

### ISSUE THREAD

**Issue by lautiamkok** [desandro/doc-ready#9]
Why do I get the error below?

Code:

```
docReady(function() {
    console.log("DOM is ready. Let's party");
});
```

Error:

```
Uncaught TypeError: Cannot read property 'bind' of undefined  doc-ready.js:61 
    at defineDocReady (doc-ready.js:61)
    at doc-ready.js:77
    at doc-ready.js:80

Uncaught ReferenceError: docReady is not defined
```

Any ideas?

**Comment by desandro** [comment]
doc-ready.js requires [eventie](https://github.com/desandro/eventie).

But if you're supporting IE9 and better, you don't need either. Use [DOMContentLoaded](https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded)
